In [6]:
import numpy
n=numpy.arange(8)
n

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
n.reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [8]:
import cv2

In [11]:
img=cv2.imread("smallgray.png",0)

In [12]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [14]:
cv2.imwrite("newpic.png",img)

True

In [16]:
img[0:1,2:4]

array([[104, 121]], dtype=uint8)

In [21]:
for i in img.flat:
    print (i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [22]:
ims=numpy.hstack((img,img))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [23]:
ims=numpy.vstack((img,img))
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [25]:
split1=numpy.vsplit(ims,3)
split1

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]